name: "Household Chores"
description: "Track your kid's chores (with allowance incentives) and your garbage pickup day"
version: "0.0.9"
slug: "household_chores"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
hassio_api: true
hassio_role: default
homeassistant_api: true
services:
  - mqtt:need
map:
  - config:rw
  - addons:rw
  - share:rw
  - backup:rw
options:
  kids:
    - id: kid1
      name: John Doe
      unit_of_measurement: $

  tasks:
    - kidid: kid1
      id: bed
      name: Do the bed
      value: 3.0

  types_of_garbage:
    - Biogut
    - Hausmüll
    - Wertstoffe
    - Paper

  garbage_translations:
    - id: Biogut
      tr: Bio
    - id: Hausmüll
      tr: Gray Garbage
    - id: Wertstoffe
      tr: Plastic
    - id: Paper
      tr: Paper

  google_service_account:
    type: ""
    project_id: ""
    private_key_id: ""
    private_key: ""
    client_email: ""
    client_id: ""
    auth_uri: ""
    token_uri: ""
    auth_provider_x509_cert_url: ""
    client_x509_url: ""

  update_interval: 43200

schema:
  google_service_account:
    type: str?
    project_id: str?
    private_key_id: str?
    private_key: str?
    client_email: str?
    client_id: str?
    auth_uri: str?
    token_uri: str?
    auth_provider_x509_cert_url: str?
    client_x509_url: str?

  kids:
    - id: str
      name: str
      unit_of_measurement: str?

  tasks:
    - kidid: str
      id: str
      name: str
      value: float

  types_of_garbage:
    - str?

  garbage_translations:
    - id: str?
      tr: str?

  update_interval: int
